name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends texlive-full --fix-missing

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error -output-directory=output src/your_resume.tex
    
    - name: Upload compiled PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: resume-pdf
        path: src/resume.pdf
